//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Model.Enum;

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class Player
    {
        public virtual int Id { get; set; }
        public virtual string UserName { get; set; }
        public virtual string Password { get; set; }
        private int level;
        public virtual int Level
        {
            get { return CalculateLevel(); }
            set { level = value; }
        }
        public virtual int ResourcesUsed { get; set; }
        public virtual IList<Planet> Planets { get; set; }
        public virtual string Token { get; set; }
        public virtual string FirstName { get; set; }
        public virtual string LastName { get; set; }
        public virtual string Email { get; set; }
        public virtual string FacebookId { get; set; }
        public virtual string LastLatitude { get; set; }
        public virtual string LastLongitude { get; set; }
        public virtual WeatherDesc WeatherDesc { get; set; }
        public virtual double WeatherWindSpeed { get; set; }

        public int CalculateLevel()
        {
            if (this.level <= 5)
            {
                return Math.Abs((ResourcesUsed - GetResourcesByLevel(this.level - 1)) / 300);
            }
            else
            {
                return Math.Abs((ResourcesUsed - GetResourcesByLevel(this.level - 1)) / 150);
            }
        }

        public int GetResourcesByLevel(int level)
        {
            if (level == 1)
            {
                return 0;
            }
            if (level <= 5)
            {
                return level * 300 + GetResourcesByLevel(level - 1);                
            }
            else
            {
                return level * 150 + GetResourcesByLevel(level - 1);
            }
        }
    }
}
